### ISSUE TITLE
hpc-utils0.0.7 

### ISSUE THREAD

**Issue by colidyre** [diegoceccarelli/json-wikipedia#14]
There is no hpc-utils 0.0.7 available.

	[ERROR] BUILD ERROR
	[INFO] ------------------------------------------------------------------------
	[INFO] Failed to resolve artifact.

	Missing:
	----------
	1) it.cnr.isti.hpc:hpc-utils:jar:0.0.7

	  Try downloading the file manually from the project website.

	  Then, install it using the command: 
	      mvn install:install-file -DgroupId=it.cnr.isti.hpc -DartifactId=hpc-utils -Dversion=0.0.7 -Dpackaging=jar -Dfile=/path/to/file

	  Alternatively, if you host your own repository you can deploy the file there: 
	      mvn deploy:deploy-file -DgroupId=it.cnr.isti.hpc -DartifactId=hpc-utils -Dversion=0.0.7 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

	  Path to dependency: 
	  	1) it.cnr.isti.hpc:json-wikipedia:jar:1.0.0
	  	2) it.cnr.isti.hpc:hpc-utils:jar:0.0.7

	----------
	1 required artifact is missing.

	for artifact: 
	  it.cnr.isti.hpc:json-wikipedia:jar:1.0.0

	from the specified remote repositories:
	  central (http://repo1.maven.org/maven2),
	  sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
	  de.tudarmstadt.ukp.wikipedia (http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots/)

Can you please update the POM or give more information how to solve that issue with a hotfix?

**Comment by diegoceccarelli** [comment]
dear @colidyre, I apologize for the delay of my answer, you were right: hpc-utils was missing. We recently updated the code and we forgot to re-add the dependency, thanks for reporting the issue. 
I fixed the pom adding a repository with the jar, so pulling the new version and running ``mvn clean compile`` should solve. Please let me know if it worked. 

Cheers,
Diego

**Comment by colidyre** [comment]
Dear @diegoceccarelli, built is successful now with jdk1.8 and (new) ```git clone https://github.com/diegoceccarelli/json-wikipedia.git``` and ```mvn assembly:assembly``` as mentioned in README. Thanks for the update!

**Comment by diegoceccarelli** [comment]
thanks for update @colidyre  and happy that we solved :+1:
