### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Luucky** [diegoceccarelli/json-wikipedia#15]
Hello, 

Can you please make the guide a little more descriptive as a newbie I have no clue how the hell I should go about installing this..

Thanks in advance!

**Comment by Luucky** [comment]
I got my head around how to do it. To make it a little easier, you could give a link to maven installation and download page:

Download: http://maven.apache.org/download.cgi
Install: http://maven.apache.org/install.html

**Comment by diegoceccarelli** [comment]
Hi @Luucky  sorry for the delay of my reply. I'll add a link into the readme. Feel free to do that and open a pull request it if you want. And do not hesitate to write/open issues if you have more questions.
Thanks,
diego
