### ISSUE TITLE
hpc-utils dependency is missing 

### ISSUE THREAD

**Issue by diegoceccarelli** [diegoceccarelli/json-wikipedia#28]
(see also #17 discussion) 
> hpc-utils is also missing from the dropbox repo specified in the pom. I fixed that in our fork by using jitpack.

The artifactory was a fixed url on my dropbox folder and dropbox decided to disable the absolute paths in September :/ let's move it to Jitpack ( as soon as I discover what is it and how it works :))

**Comment by diegoceccarelli** [comment]
very cool indeed 👍

**Comment by tgalery** [comment]
close due to merge
