### ISSUE TITLE
Create jar with dependency using `maven-shade-plugin` instead of assembly

### ISSUE THREAD

**Issue by diegoceccarelli** [diegoceccarelli/json-wikipedia#45]
At the moment we use the goal `assebly:assembly` to produce a jar with all the dependency. 

`maven-shade-plugin` is better than `assembly` http://2mohitarora.blogspot.com/2011/12/maven-shade-plugin-better-than-maven.html and it will produce that jar when running the normal maven target `package`. 

Also set it up so that the main can be run from the jar. Example here: http://maven.apache.org/plugins/maven-shade-plugin/examples/executable-jar.html

**Comment by sparrowV** [comment]
@diegoceccarelli  can u assign this to me?

**Comment by diegoceccarelli** [comment]
@sparrowV done, thanks!
