### ISSUE TITLE
Links with empty Anchors

### ISSUE THREAD

**Issue by dav009** [diegoceccarelli/json-wikipedia#5]
There are links with empty descriptions.
Looking at the code there is a comment `When anchor is empty, it means is the same of id`.
Which sort of makes sense since they look like: `[[wikipedia_article]]`. [1]

so when one does `getDescription()` links with empty descriptions would return their id. However when the object gets serialised to json the `description` field will be empty

As an user of jsonwikipedia this looked a bit weird at the beginning. I think the serialised description should equal `getDescription`.
If you agree on this point I can make a PR. 

[1] https://github.com/diegoceccarelli/json-wikipedia/blob/master/src/main/java/it/cnr/isti/hpc/wikipedia/article/Link.java#L53

**Comment by diegoceccarelli** [comment]
@dav009 nice catch :+1:  ! Happy to accept a PR :)

**Comment by diegoceccarelli** [comment]
@dav009  I think that it would make sense to perform the check during the conversion and then trasform getDescription in a simple access method.
